image: golang:alpine

cache:
  paths:
    - /go/src/
stages:
  - test
  - deploy

test:
  stage: test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'
  script:
    - CGO_ENABLED=0 go test ./...

deploy-latest:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  image: docker:stable
  services:
    - name: docker:stable-dind
      command: [ "--experimental" ]
  script:
    - ./ci-deploy.sh latest
